---
- name: restart sshd
  ansible.builtin.service:
    state: restarted
    name: sshd
  when: takel_ssh_run_handler

- name: read /etc/ssh/ssh_host_ecdsa_key
  ansible.builtin.slurp:
    src: /etc/ssh/ssh_host_ecdsa_key
  register: ssh_host_ecdsa_key
  listen: show takel_ssh_host_ecdsa_key

- name: takel_ssh_host_ecdsa_key
  ansible.builtin.debug:
    msg: "{{ ssh_host_ecdsa_key.content | b64decode }}"
  listen: show takel_ssh_host_ecdsa_key

- name: read /etc/ssh/ssh_host_ecdsa_key.pub
  ansible.builtin.slurp:
    src: /etc/ssh/ssh_host_ecdsa_key.pub
  register: ssh_host_ecdsa_key_pub
  listen: show takel_ssh_host_ecdsa_key_pub

- name: takel_ssh_host_ecdsa_key_pub
  ansible.builtin.debug:
    msg: "{{ ssh_host_ecdsa_key_pub.content | b64decode }}"
  listen: show takel_ssh_host_ecdsa_key_pub

- name: read /etc/ssh/ssh_host_ed25519_key
  ansible.builtin.slurp:
    src: /etc/ssh/ssh_host_ed25519_key
  register: ssh_host_ed25519_key
  listen: show takel_ssh_host_ed25519_key

- name: takel_ssh_host_ed25519_key
  ansible.builtin.debug:
    msg: "{{ ssh_host_ed25519_key.content | b64decode }}"
  listen: show takel_ssh_host_ed25519_key

- name: read /etc/ssh/ssh_host_ed25519_key.pub
  ansible.builtin.slurp:
    src: /etc/ssh/ssh_host_ed25519_key.pub
  register: ssh_host_ed25519_key_pub
  listen: show takel_ssh_host_ed25519_key_pub

- name: takel_ssh_host_ed25519_key_pub
  ansible.builtin.debug:
    msg: "{{ ssh_host_ed25519_key_pub.content | b64decode }}"
  listen: show takel_ssh_host_ed25519_key_pub

- name: read /etc/ssh/ssh_host_rsa_key
  ansible.builtin.slurp:
    src: /etc/ssh/ssh_host_rsa_key
  register: ssh_host_rsa_key
  listen: show takel_ssh_host_rsa_key

- name: takel_ssh_host_rsa_key
  ansible.builtin.debug:
    msg: "{{ ssh_host_rsa_key.content | b64decode }}"
  listen: show takel_ssh_host_rsa_key

- name: read /etc/ssh/ssh_host_rsa_key.pub
  ansible.builtin.slurp:
    src: /etc/ssh/ssh_host_rsa_key.pub
  register: ssh_host_rsa_key_pub
  listen: show takel_ssh_host_rsa_key_pub

- name: takel_ssh_host_rsa_key_pub
  ansible.builtin.debug:
    msg: "{{ ssh_host_rsa_key_pub.content | b64decode }}"
  listen: show takel_ssh_host_rsa_key_pub
